Repository fourkitchens/emulsify-gulp, pull requests merged in 2018-12, with the labels that each got.

#94 ghostMode in gulp-config and browserSync init
  gulp-config.js
  index.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#92 91 Add theme images directory and theme logo to GitHub pages deployment
  gulp-config.js
  index.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#99 Update dependencies
  gulp-tasks/gulp-css.js
  gulp-tasks/gulp-pattern-lab.js
  gulp-tasks/gulp-tests.js
  gulp-tasks/notifier.js
  gulp-tasks/pa11y.js
  index.js
  package-lock.json
  package.json
  yarn.lock
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review, Status: Shipit

#101 100: Clean CSS - option to disable or set default options
  gulp-config.js
  gulp-tasks/gulp-css.js
Labels: Priority: Low, Status: Review Needed
